services:
  tgbot-rss:
    container_name: rssbot
    image: rssbot:latest
    build:
      context: .
      dockerfile: Docker/Dockerfile
    restart: unless-stopped
    environment:
      BotToken: "${BotToken:-}"
      ADMINIDS: "${ADMINIDS:-0}"
      Cycletime: "${Cycletime:-300}"
      Debug: "${Debug:-false}"
      ProxyURL: "${ProxyURL:-}"
      Pushinfo: "${Pushinfo:-}"
      TZ: "${TZ:-Asia/Shanghai}"
    volumes:
      - "./data:/data/"
